import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { Metadata } from "next/types";

import "./globals.css";

export const metadata: Metadata = {
  title: "mindofwaves",
  description: "Generated by waves",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <body className="antialiased">
        <main className="w-screen h-screen">{children}</main>
      </body>
    </html>
  );
}
